name: Test

on:
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
      - name: Download dependencies
        run: flutter pub get
      - name: Create .env with server URL
        run: echo "API_LOGIN_URL =  ${{ secrets.API_LOGIN_URL }}" > .env
      - name: Build apk
        run: flutter build apk
      - name: Build appbundle
        run: flutter build appbundle
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
      - name: Download dependencies
        run: flutter pub get
      - name: Set up docker environment
        run: docker compose up -d
      - name: Create env with server URL
        run: echo "API_LOGIN_URL =  http://127.0.0.1:8080" > env
      - name: Run tests
        run: flutter test
      - name: Clean docker environment
        run: docker compose down --rmi all -v --remove-orphans